GET http://localhost:3000/todos/

###
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 6,
  "todo": "Do the Assignment",
  "priority": "MEDIUM",
  "status": "DONE"
}

###
PUT http://localhost:3000/todos/6
Content-Type: application/json

{
    "priority": "HIGH"
}

###
DELETE http://localhost:3000/todos/6